### ISSUE TITLE
Bug with the detection file

### ISSUE THREAD

**Issue by Drosscend** [levan92/deep_sort_realtime#38]
Hello, 
I have an error when calling `update_tracks`
Here is the error returned:
`AttributeError: module 'numpy' has no attribute 'float'`

It is located in the `detection.py` file at line 35.

I use numpy version **1.24.1** and python version **3.9**

Thank you in advance

**Comment by Drosscend** [comment]
Result of `python3 -m unittest` :

```
FRAME1
E
FRAME1
EssssTesting pytorch embedder
close: 0.012196660041809082 vs diff: 0.4409685730934143
.Testing pytorch embedder
close: 0.012196660041809082 vs diff: 0.4409685730934143
.ss
FRAME1
Es
======================================================================
ERROR: test_hbb (test.test_bb.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\deep_sort_realtime\test\test_bb.py", line 51, in test_hbb
    tracks = tracker.update_tracks(
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 202, in update_tracks
    detections = self.create_detections(raw_detections, embeds, instance_masks=instance_masks, others=others)
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 256, in create_detections
    Detection(
  File "E:\deep_sort_realtime\deep_sort_realtime\deep_sort\detection.py", line 37, in __init__
    self.ltwh = np.asarray(ltwh, dtype=np.float)
  File "E:\deep_sort_realtime\test\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

======================================================================
ERROR: test_obb (test.test_bb.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\deep_sort_realtime\test\test_bb.py", line 154, in test_obb
    tracks = tracker.update_tracks(detections1, frame=frame1, embeds=embeds)
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 210, in update_tracks
    detections = self.create_detections_poly(
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 276, in create_detections_poly
    Detection(bbox, score, embed, class_name=cl, others=raw_polygon)
  File "E:\deep_sort_realtime\deep_sort_realtime\deep_sort\detection.py", line 37, in __init__
    self.ltwh = np.asarray(ltwh, dtype=np.float)
  File "E:\deep_sort_realtime\test\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

======================================================================
ERROR: test_base (test.test_general.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\deep_sort_realtime\test\test_general.py", line 49, in test_base
    tracks = tracker.update_tracks(
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 202, in update_tracks
    detections = self.create_detections(raw_detections, embeds, instance_masks=instance_masks, others=others)
  File "E:\deep_sort_realtime\deep_sort_realtime\deepsort_tracker.py", line 256, in create_detections
    Detection(
  File "E:\deep_sort_realtime\deep_sort_realtime\deep_sort\detection.py", line 37, in __init__
    self.ltwh = np.asarray(ltwh, dtype=np.float)
  File "E:\deep_sort_realtime\test\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

----------------------------------------------------------------------
Ran 12 tests in 2.809s

FAILED (errors=3, skipped=7)
```

**Comment by Drosscend** [comment]
When I put `np.float32` instead of `np.float` there is no more problem

**Comment by levan92** [comment]
Hi @Drosscend, thanks for your bug report. Should be due to a numpy version mismatch, since np.float has been deprecated. I've pushed a latest commit to fix that. Thanks!
